app/models.py
from app import db, login_manager
from flask_login import UserMixin

@login_manager.user_loader
def current_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(84), nullable=False)
    email = db.Column(db.String(84), nullable=False, unique=True, index=True)
    password = db.Column(db.String(255), nullable=False)

    def __str__(self):
        return self.name

app/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.html5 import EmailField
from wtforms.fields import PasswordField, SubmitField, StringField
from wtforms.validators import Email, Length, DataRequired


class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[
        Email()
    ])
    password = PasswordField("Senha", validators=[
        Length(3, 6, "O campo deve conter de 3 a 6 caracteres")
    ])
    submit = SubmitField("Logar")



class RegisterForm(FlaskForm):
    name = StringField("Nome", validators=[
        DataRequired("O campo é obrigatório")
    ])
    email = EmailField("Email", validators=[
        Email()
    ])
    password = PasswordField("Senha", validators=[
        Length(3, 6, "O campo deve conter de 3 a 6 caracteres")
    ])
    submit = SubmitField("Registrar")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()
login_manager = LoginManager()


bootstrap = Bootstrap()


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "SECRET"
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///app.db"
    app.config["SQLALCHEMT_TRACK_MODIFICATIONS"] = False


    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)


    from app import routes
    routes.init_app(app) #Criando as rotas do app


    return app

app/routes.py
from app.auth import auth as auth_blueprint
from app.user import user as user_blueprint




def init_app(app):

    app.register_blueprint(auth_blueprint)
    app.register_blueprint(user_blueprint)

app/user/__init__.py
from flask import Blueprint

user = Blueprint("user", __name__)

from . import views 

app/user/views.py
from . import user
from flask_login import login_required
from flask import render_template
from app.models import User


@user.route("/")
def index():
    users = User.query.all()
    return render_template("index.html", users=users)



@user.route('/user/<int:id>')
@login_required
def unique(id):
    user = User.query.get(id)
    return render_template("user.html", user=user)

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hangetsu</title>


    {% block styles %}
      <!-- Bootstrap CSS -->
      {{ bootstrap.load_css() }}
    {% endblock %}



</head>
<body>

    {% include "nav.html" %}


    <div class="container">
        {% block content %} {% endblock %}
    </div>


    {% block scripts %}
            <!-- Optional JavaScript -->
            {{ bootstrap.load_js() }}
        {% endblock %}

    
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}

    {% for user in users %}
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <a href="{{ url_for('user.unique', id=user.id) }}">
                    {{ user.name }}
                </a>
            </li>
        </ul>
    {% endfor %}

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% from "bootstrap/form.html" import render_form %}

{% block content %}
    {{ render_form(form) }}
{% endblock %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('user.index') }}">Hangetsu</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('user.index') }}">Início</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Produtos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contato</a>
          </li>

          {% if not current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

app/templates/register.html
{% extends "base.html" %}
{% from "bootstrap/form.html" import render_form %}

{% block content %}
    {{ render_form(form) }}
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block content %}
    <div>
        <table class="table table-striped">
            <tbody>
                <td>
                    {{ user.id }}
                </td>
                <td>
                    {{ user.name }}
                </td>
                <td>
                    {{ user.email }}
                </td>
            </tbody>
        </table>
    </div>
{% endblock %}